### ISSUE TITLE
disabled global actions are still blocking after a new lxqt session

### ISSUE THREAD

**Issue by Loader009** [lxqt/lxqt-globalkeys#173] opened 2020-08-02 18:56 UTC
I disabled all CTRL+F## keys in the manager, I don't need them.
But after any reboot the CTRL+F5 doesn't behave how it should - though, all CTRL+F## keys are still disabled.
If I enable and disable CTRL+F5 in the manager, everything is fine again until the next reboot.

##### Expected Behavior
CTRL+F5 should be applied to the browser, doing a whole cache-refresh.

##### Current Behavior
CTRL+F5 is not applied to the browser, instead does "kind" of nothing, firefox behaves like CTRL+F5 is enabled.
But on CTRL+2 or CTRL+1 nothing happens, no desktop switch.

##### Possible Solution
--

##### Steps to Reproduce (for bugs)
1. start your lxqt session
2. start firefox, open any website
3. press CTRL+F5 in order to reload the cache
4. it should reload the whole website, but it doesn't

##### Context
I use µMatrix and I need to refresh the cache if I allow a frame.
If there is any website error because of blocked cookies, CTRL+F5 also helps often.

##### System Information
* Distribution & Version: EndeavourOS Linux x86_64 (based on ArchLinux)
* Kernel: 5.7.11.a-1-hardened
* Qt Version: 5.15.0
* liblxqt Version: 0.15.1-1
* lxqt-build-tools Version: -- (stable version atm)
* Package version: lxqt-globalkeys 0.15.0-1
* windows manager: openbox

**Comment by Loader009** [comment] 2020-08-02 18:56
I might switch to the git version later, to be more updated.

**Comment by tsujan** [comment] 2020-08-02 19:12
> I disabled all CTRL+F## keys in the manager... CTRL+F5 is not applied to the browser, instead it tries to switch to desktop 5 (which isn't set up).

Then, it should be set by your window manager -- whatever it is -- independently of `lxqt-globalkeys`.

**Comment by Loader009** [comment] 2020-08-02 19:22
> > I disabled all CTRL+F## keys in the manager... CTRL+F5 is not applied to the browser, instead it tries to switch to desktop 5 (which isn't set up).
> 
> Then, it should be set by your window manager -- whatever it is -- independently of `lxqt-globalkeys`.

Openbox (sorry, forgot that)
But I can't find anything about keyshortcuts in openbox.

**Comment by Loader009** [comment] 2020-08-02 19:44
Another note I forgot:
If I enabled e.g. CTRL+F5 and disable it again, it works as intended.

**Comment by tsujan** [comment] 2020-08-02 19:45
I checked `Ctrl+F5` in Firefox. It works without problem here (I have KWin but that shouldn't make a difference).

If you're sure that `Ctrl+F5` is disabled in Global Actions Manager and isn't used by Openbox in its config file, I have no idea why it doesn't work for you.

**Comment by tsujan** [comment] 2020-08-02 19:49
Wait a minute! Something is wrong here too. I logged out and logged it again. Then, `Ctrl+F5` stopped working in Firefox!

Now that we both see the same problem, it should be a bug somewhere.

**Comment by tsujan** [comment] 2020-08-02 19:56
Ctrl+F5 is definitely disabled here:

![ctrl-f5](https://user-images.githubusercontent.com/981076/89131108-9c3a7280-d51f-11ea-9e0f-e6ef59599a67.png)

It'll start to work in Firefox if I enable and disable it again in Global Actions Manager, exactly as @Loader009 said.

**Comment by Loader009** [comment] 2020-08-02 20:08
phew, thank you, I already began to look in openbox' config, nothing for C-F5 set.

**Comment by tsujan** [comment] 2020-08-02 20:18
> I already began to look in openbox' config, nothing for C-F5 set.

I checked its default xml config file and it didn't contain C-F5. Anyway, since I use KWin, it can't be about Openbox. Sorry if I caused a confusion!

**Comment by tsujan** [comment] 2020-08-02 21:52
The strange thing is that all `Ctrl+Fxxx` shortcuts are really disabled -- they don't switch desktop here -- but `Ctrl+F5` is taken away from Firefox, Chromium and other browsers. I think `Ctrl+Fxxx` may not work anywhere but I haven't had the time to test.

**Comment by Loader009** [comment] 2020-08-03 05:32
Yes, tested this right now, the same behavior.
I will update the first message.

**Comment by tsujan** [comment] 2020-08-03 08:05
Today, I tested `Ctrl+Fx` in the key press event of a source code. It didn't work under LXQt while it worked fine under KDE. Very bad!

**Comment by tsujan** [comment] 2020-08-03 17:37
Found the cause:

`Core::addOrRegisterClientAction` is called twice. The first time, it's followed by `Core::enableActionNonGuarded`, which disables the shortcut that's marked as disabled. The second time, it's called by `Core::addClientAction` and grabs the key, without checking whether the shortcut is enabled or not. Therefore, a simple check fixes the problem.

Before making a PR, I should see if a better solution exists. This bug should be very old and yet, no one had noticed it before!

**Comment by Loader009** [comment] 2020-08-03 17:44
I use lxqt since a few days (about thursday I switched to EndeavourOS with lxqt), since then I am setting everything up and notice bugs here and there. You might see my name more in the future.

I will switch to building from github soon, I just need some time to catch up some things.

**Comment by tsujan** [comment] 2020-08-03 17:54
> since then I am setting everything up and notice bugs here and there. You might see my name more in the future.

We appreciate good bug reports like this one. If you find any bug in any LXQt component, please don't hesitate to report it after searching in open issues.

**Comment by tsujan** [comment] 2020-08-03 22:28
@Loader009 
The simple PR is https://github.com/lxqt/lxqt-globalkeys/pull/174. It fixes the problem here but could you please test it too?

While testing the fix, I found another bug, that isn't as important as this. I'll open an issue page for it later.

**Comment by Loader009** [comment] 2020-08-04 05:35
@tsujan thx, I will do a single build of globalkeys and I hope that it will work with the current installed lxqt version.
Though, not now, in about 10h I hopefully will have time for this.

**Comment by tsujan** [comment] 2020-08-04 12:11
> Though, not now,...

Take your time.

Please also confirm https://github.com/lxqt/lxqt-globalkeys/issues/175 on its page! It's the other bug I mentioned above.

**Comment by Loader009** [comment] 2020-08-04 17:11
@tsujan yes, your commit fixes this issue.
Thank you!

**Closed** 2020-09-04 10:08 UTC
Labels: bug
