### ISSUE TITLE
Close Button not working in lxqt-config-globalkeyshortcuts

### ISSUE THREAD

**Issue by kellerleicheorig** [lxqt/lxqt-globalkeys#107] opened 2019-01-28 17:09 UTC
Hi,

I build all packages and find out, that the close button doesn't work in Version 0.14.0. 
Some information about my system are:

LXQt Version | 0.14.0
Qt | 5.11.3
Kernel: 4.20.3
Distro: PCLinuxOS 2019

Regards
Daniel

**Comment by agaida** [comment] 2019-02-23 16:08
* Reproducible in debian/sid and experimental-snapshots 
* Reproducible in arch (latest git)
* Reproducible in antergos (was  lxqt/lxqt/issues/1674)

Erm - @tsujan @palinek - i guess we have a problem here that we should not ignore.

**Comment by tsujan** [comment] 2019-02-23 16:08
Mine is OK but I didn't update it with https://github.com/lxqt/lxqt-globalkeys/commit/49fb67313a194aa2e6c84c9911b5f349626921a0 ; please see if that's the cause and reverse it if so.

**Comment by tsujan** [comment] 2019-02-23 16:11
And before cursing me: only now I realized that I hadn't included that commit in my installation.

**Comment by agaida** [comment] 2019-02-23 16:17
Me? Cursing? Never, i'm to shy ...

**Comment by tsujan** [comment] 2019-02-23 16:21
Ha ha.. I didn't approve of the PR: https://github.com/lxqt/lxqt-globalkeys/pull/101

Tell me if it's really the cause!

**Comment by tsujan** [comment] 2019-02-23 16:46
OK, no test is needed; that commit is definitely the cause because "MainWindow" is used in another place of the same file for closing the window. Actually, even if it didn't cause a bug, it would be completely useless.

It should be reversed and a point release will be good as soon as possible.

**Comment by agaida** [comment] 2019-02-23 16:47
Obvious - it was. 

... My dog ​​has no legs and no name. Why? If I call him, he will not come anyway. ...

My bad, i read it in the pull request as only setting the display name - not something that would require a full refactoring.

**Comment by tsujan** [comment] 2019-02-23 16:49
Mistakes happen but, of course, we'll be more cautious when receiving another PR from the same person.

**Comment by agaida** [comment] 2019-02-23 16:51
Glad that you don't take that commit. - Re point releases, that was the last important bug i'm aware of, so i would prepare and roll out some points today.

**Comment by tsujan** [comment] 2019-02-23 16:53
> ... so i would prepare and roll out some points today.

Don't hesitate to tell me if I can be of any help.

BTW, point releases are nice whenever there are important bugs that are fixed.

**Closed** 2019-02-23 16:54 UTC
